name: .NET Console App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      working-directory: ./src
      run: dotnet publish -c Release -o ./publish

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: ./publish
